export const FILTER = 'FILTER';
export const SHOW_MODAL_ADD_DATASET = 'SHOW_MODAL_ADD_DATASET';
export const SHOW_MODAL_ADD_ALGORITHM = 'SHOW_MODAL_ADD_ALGORITHM';
export const TOGGLE_DRAWER_BAR = 'TOGGLE_DRAWER_BAR';
export const DATASET_STATUS = 'DATASET_STATUS';

// Async
export const GET_DATASETS = 'GET_DATASETS';
export const GET_DATASETS_RECEIVED = 'GET_DATASETS_RECEIVED';

export const GET_DATASET = 'GET_DATASET';
export const GET_DATASET_SUCCESS = 'GET_DATASET_SUCCESS';

export const POST_DATASET = 'POST_DATASET';
export const POST_DATASET_SUCCESS = 'POST_DATASET_SUCCESS';
export const POST_DATASET_ERROR = 'POST_DATASET_ERROR';

export const DELETE_DATASET = 'DELETE_DATASET';
export const DELETE_DATASET_SUCCESS = 'DELETE_DATASET_SUCCESS';

export const PUT_DATASET = 'PUT_DATASET';
export const PUT_DATASET_SUCCESS = 'PUT_DATASET_SUCCESS';
export const PUT_DATASET_ERROR = 'PUT_DATASET_ERROR';

export const GENERATE_TRIPLES = 'GENERATE_TRIPLES';

export const GET_TASK = 'GET_TASK';
export const GET_TASK_ERROR = 'GET_TASK_ERROR';
export const GET_TASK_RECEIVED = 'GET_TASK_RECEIVED';

export const GET_ALGORITHMS = 'GET_ALGORITHMS';
export const GET_ALGORITHMS_RECEIVED = 'GET_ALGORITHMS_RECEIVED';

export const GET_ALGORITHM  = 'GET_ALGORITHM';
export const GET_ALGORITHM_RECEIVED = 'GET_ALGORITHM_RECEIVED';

export const POST_ALGORITHM = 'POST_ALGORITHM';
export const POST_ALGORITHM_SUCCESS = 'POST_ALGORITHM_SUCCESS';

export const TRAIN_DATASET = 'TRAIN_DATASET';

export const GET_SUGGESTIONS = 'GET_SUGGESTIONS';
export const GET_SUGGESTIONS_RECEIVED = 'GET_SUGGESTIONS_RECEIVED';
