export const FILTER = 'FILTER';
export const SHOW_MODAL_ADD_DATASET = 'SHOW_MODAL_ADD_DATASET';
export const TOGGLE_DRAWER_BAR = 'TOGGLE_DRAWER_BAR';

// Async
export const GET_DATASETS = 'GET_DATASETS';
export const GET_DATASETS_RECEIVED = 'GET_DATASETS_RECEIVED';

export const POST_DATASET = 'POST_DATASET';
export const POST_DATASET_SUCCESS = 'POST_DATASET_SUCCESS';
export const POST_DATASET_ERROR = 'POST_DATASET_ERROR';
